/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArbitrationDAOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "appeal"
      | "appealPeriod"
      | "cancelCase"
      | "caseCount"
      | "caseDeposit"
      | "caseVoters"
      | "cases"
      | "claimReward"
      | "createCase"
      | "daoVotingPeriod"
      | "feedToken"
      | "getCaseStats"
      | "getCaseVoters"
      | "minVoteStake"
      | "owner"
      | "quorumPercent"
      | "renounceOwnership"
      | "resolveCase"
      | "setCaseDeposit"
      | "setMinVoteStake"
      | "setVotingPeriod"
      | "transferOwnership"
      | "vote"
      | "votes"
      | "votingPeriod"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CaseAppealed"
      | "CaseCreated"
      | "CaseResolved"
      | "ConfigUpdated"
      | "OwnershipTransferred"
      | "RewardClaimed"
      | "Voted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "appeal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "appealPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelCase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "caseCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "caseDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "caseVoters",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "cases", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCase",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "daoVotingPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feedToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCaseStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCaseVoters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minVoteStake",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quorumPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveCase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCaseDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinVoteStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVotingPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "votingPeriod",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "appeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "appealPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelCase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "caseCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "caseDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "caseVoters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cases", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createCase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feedToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCaseStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCaseVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minVoteStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quorumPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveCase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCaseDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinVoteStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingPeriod",
    data: BytesLike
  ): Result;
}

export namespace CaseAppealedEvent {
  export type InputTuple = [caseId: BigNumberish, appellant: AddressLike];
  export type OutputTuple = [caseId: bigint, appellant: string];
  export interface OutputObject {
    caseId: bigint;
    appellant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CaseCreatedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    plaintiff: AddressLike,
    defendant: AddressLike,
    orderId: string
  ];
  export type OutputTuple = [
    caseId: bigint,
    plaintiff: string,
    defendant: string,
    orderId: string
  ];
  export interface OutputObject {
    caseId: bigint;
    plaintiff: string;
    defendant: string;
    orderId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CaseResolvedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    outcome: BigNumberish,
    supportStake: BigNumberish,
    opposeStake: BigNumberish
  ];
  export type OutputTuple = [
    caseId: bigint,
    outcome: bigint,
    supportStake: bigint,
    opposeStake: bigint
  ];
  export interface OutputObject {
    caseId: bigint;
    outcome: bigint;
    supportStake: bigint;
    opposeStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfigUpdatedEvent {
  export type InputTuple = [param: string, value: BigNumberish];
  export type OutputTuple = [param: string, value: bigint];
  export interface OutputObject {
    param: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    voter: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [caseId: bigint, voter: string, reward: bigint];
  export interface OutputObject {
    caseId: bigint;
    voter: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    voter: AddressLike,
    voteType: BigNumberish,
    stake: BigNumberish
  ];
  export type OutputTuple = [
    caseId: bigint,
    voter: string,
    voteType: bigint,
    stake: bigint
  ];
  export interface OutputObject {
    caseId: bigint;
    voter: string;
    voteType: bigint;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArbitrationDAO extends BaseContract {
  connect(runner?: ContractRunner | null): ArbitrationDAO;
  waitForDeployment(): Promise<this>;

  interface: ArbitrationDAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  appeal: TypedContractMethod<[_caseId: BigNumberish], [void], "nonpayable">;

  appealPeriod: TypedContractMethod<[], [bigint], "view">;

  cancelCase: TypedContractMethod<
    [_caseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  caseCount: TypedContractMethod<[], [bigint], "view">;

  caseDeposit: TypedContractMethod<[], [bigint], "view">;

  caseVoters: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  cases: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        plaintiff: string;
        defendant: string;
        orderId: string;
        evidence: string;
        deposit: bigint;
        createdAt: bigint;
        votingDeadline: bigint;
        supportStake: bigint;
        opposeStake: bigint;
        abstainStake: bigint;
        voterCount: bigint;
        status: bigint;
        appealed: boolean;
        outcome: bigint;
      }
    ],
    "view"
  >;

  claimReward: TypedContractMethod<
    [_caseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCase: TypedContractMethod<
    [_defendant: AddressLike, _orderId: string, _evidence: string],
    [bigint],
    "nonpayable"
  >;

  daoVotingPeriod: TypedContractMethod<[], [bigint], "view">;

  feedToken: TypedContractMethod<[], [string], "view">;

  getCaseStats: TypedContractMethod<
    [_caseId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        supportStake: bigint;
        opposeStake: bigint;
        abstainStake: bigint;
        voterCount: bigint;
        status: bigint;
        outcome: bigint;
      }
    ],
    "view"
  >;

  getCaseVoters: TypedContractMethod<
    [_caseId: BigNumberish],
    [string[]],
    "view"
  >;

  minVoteStake: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  quorumPercent: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveCase: TypedContractMethod<
    [_caseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCaseDeposit: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinVoteStake: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVotingPeriod: TypedContractMethod<
    [_period: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [_caseId: BigNumberish, _voteType: BigNumberish, _stake: BigNumberish],
    [void],
    "nonpayable"
  >;

  votes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        voter: string;
        voteType: bigint;
        stake: bigint;
        votedAt: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  votingPeriod: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "appeal"
  ): TypedContractMethod<[_caseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "appealPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelCase"
  ): TypedContractMethod<[_caseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "caseCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "caseDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "caseVoters"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "cases"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        plaintiff: string;
        defendant: string;
        orderId: string;
        evidence: string;
        deposit: bigint;
        createdAt: bigint;
        votingDeadline: bigint;
        supportStake: bigint;
        opposeStake: bigint;
        abstainStake: bigint;
        voterCount: bigint;
        status: bigint;
        appealed: boolean;
        outcome: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[_caseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createCase"
  ): TypedContractMethod<
    [_defendant: AddressLike, _orderId: string, _evidence: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "daoVotingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feedToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCaseStats"
  ): TypedContractMethod<
    [_caseId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        supportStake: bigint;
        opposeStake: bigint;
        abstainStake: bigint;
        voterCount: bigint;
        status: bigint;
        outcome: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCaseVoters"
  ): TypedContractMethod<[_caseId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "minVoteStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quorumPercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveCase"
  ): TypedContractMethod<[_caseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCaseDeposit"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinVoteStake"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVotingPeriod"
  ): TypedContractMethod<[_period: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_caseId: BigNumberish, _voteType: BigNumberish, _stake: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        voter: string;
        voteType: bigint;
        stake: bigint;
        votedAt: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "votingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CaseAppealed"
  ): TypedContractEvent<
    CaseAppealedEvent.InputTuple,
    CaseAppealedEvent.OutputTuple,
    CaseAppealedEvent.OutputObject
  >;
  getEvent(
    key: "CaseCreated"
  ): TypedContractEvent<
    CaseCreatedEvent.InputTuple,
    CaseCreatedEvent.OutputTuple,
    CaseCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CaseResolved"
  ): TypedContractEvent<
    CaseResolvedEvent.InputTuple,
    CaseResolvedEvent.OutputTuple,
    CaseResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ConfigUpdated"
  ): TypedContractEvent<
    ConfigUpdatedEvent.InputTuple,
    ConfigUpdatedEvent.OutputTuple,
    ConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "CaseAppealed(uint256,address)": TypedContractEvent<
      CaseAppealedEvent.InputTuple,
      CaseAppealedEvent.OutputTuple,
      CaseAppealedEvent.OutputObject
    >;
    CaseAppealed: TypedContractEvent<
      CaseAppealedEvent.InputTuple,
      CaseAppealedEvent.OutputTuple,
      CaseAppealedEvent.OutputObject
    >;

    "CaseCreated(uint256,address,address,string)": TypedContractEvent<
      CaseCreatedEvent.InputTuple,
      CaseCreatedEvent.OutputTuple,
      CaseCreatedEvent.OutputObject
    >;
    CaseCreated: TypedContractEvent<
      CaseCreatedEvent.InputTuple,
      CaseCreatedEvent.OutputTuple,
      CaseCreatedEvent.OutputObject
    >;

    "CaseResolved(uint256,uint8,uint256,uint256)": TypedContractEvent<
      CaseResolvedEvent.InputTuple,
      CaseResolvedEvent.OutputTuple,
      CaseResolvedEvent.OutputObject
    >;
    CaseResolved: TypedContractEvent<
      CaseResolvedEvent.InputTuple,
      CaseResolvedEvent.OutputTuple,
      CaseResolvedEvent.OutputObject
    >;

    "ConfigUpdated(string,uint256)": TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;
    ConfigUpdated: TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardClaimed(uint256,address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "Voted(uint256,address,uint8,uint256)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
