/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FeedEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "authorizedProtocols"
      | "awardXP"
      | "consensus"
      | "engineOrders"
      | "feedRequests"
      | "feedToken"
      | "feederLicense"
      | "feeders"
      | "getConsensusPrice"
      | "getFeederInfo"
      | "getOrderFeeders"
      | "grabOrder"
      | "initialize"
      | "isProtocolAuthorized"
      | "maxDailyGrabByRank"
      | "minStakeByRank"
      | "owner"
      | "proxiableUUID"
      | "registerFeeder"
      | "renounceOwnership"
      | "requestFeed"
      | "requestUnstake"
      | "rewardPenalty"
      | "setAuthorizedProtocol"
      | "settleOrder"
      | "stake"
      | "totalFeeders"
      | "transferOwnership"
      | "unstakeCooldown"
      | "updateMinStake"
      | "updateSubContracts"
      | "updateUnstakeCooldown"
      | "upgradeToAndCall"
      | "withdraw"
      | "xpThresholds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeedRequested"
      | "FeederRankUpdated"
      | "FeederRegistered"
      | "Initialized"
      | "OrderGrabbed"
      | "OrderSettled"
      | "OwnershipTransferred"
      | "ProtocolAuthorized"
      | "Staked"
      | "UnstakeRequested"
      | "Upgraded"
      | "Withdrawn"
      | "XPAwarded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedProtocols",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "awardXP",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "consensus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "engineOrders",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feedRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "feedToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feederLicense",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConsensusPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeederInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderFeeders",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grabOrder",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProtocolAuthorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxDailyGrabByRank",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minStakeByRank",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerFeeder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestFeed",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestUnstake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPenalty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedProtocol",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "settleOrder",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "totalFeeders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateMinStake",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSubContracts",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUnstakeCooldown",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "xpThresholds",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedProtocols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "awardXP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "consensus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "engineOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feedRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feedToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feederLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getConsensusPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeederInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderFeeders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grabOrder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isProtocolAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDailyGrabByRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minStakeByRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFeeder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUnstake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalFeeders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMinStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSubContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUnstakeCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "xpThresholds",
    data: BytesLike
  ): Result;
}

export namespace FeedRequestedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    requester: AddressLike,
    requiredFeeders: BigNumberish,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    requester: string,
    requiredFeeders: bigint,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    orderId: string;
    requester: string;
    requiredFeeders: bigint;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeederRankUpdatedEvent {
  export type InputTuple = [
    feeder: AddressLike,
    oldRank: BigNumberish,
    newRank: BigNumberish
  ];
  export type OutputTuple = [feeder: string, oldRank: bigint, newRank: bigint];
  export interface OutputObject {
    feeder: string;
    oldRank: bigint;
    newRank: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeederRegisteredEvent {
  export type InputTuple = [feeder: AddressLike, licenseTokenId: BigNumberish];
  export type OutputTuple = [feeder: string, licenseTokenId: bigint];
  export interface OutputObject {
    feeder: string;
    licenseTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderGrabbedEvent {
  export type InputTuple = [orderId: BytesLike, feeder: AddressLike];
  export type OutputTuple = [orderId: string, feeder: string];
  export interface OutputObject {
    orderId: string;
    feeder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSettledEvent {
  export type InputTuple = [
    orderId: BytesLike,
    consensusPrice: BigNumberish,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    consensusPrice: bigint,
    reward: bigint
  ];
  export interface OutputObject {
    orderId: string;
    consensusPrice: bigint;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolAuthorizedEvent {
  export type InputTuple = [protocol: AddressLike, authorized: boolean];
  export type OutputTuple = [protocol: string, authorized: boolean];
  export interface OutputObject {
    protocol: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [feeder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [feeder: string, amount: bigint];
  export interface OutputObject {
    feeder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakeRequestedEvent {
  export type InputTuple = [feeder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [feeder: string, amount: bigint];
  export interface OutputObject {
    feeder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [feeder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [feeder: string, amount: bigint];
  export interface OutputObject {
    feeder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XPAwardedEvent {
  export type InputTuple = [
    feeder: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [feeder: string, amount: bigint, reason: string];
  export interface OutputObject {
    feeder: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FeedEngine extends BaseContract {
  connect(runner?: ContractRunner | null): FeedEngine;
  waitForDeployment(): Promise<this>;

  interface: FeedEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  authorizedProtocols: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  awardXP: TypedContractMethod<
    [feederAddr: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  consensus: TypedContractMethod<[], [string], "view">;

  engineOrders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean] & {
        orderId: string;
        rewardAmount: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;

  feedRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        requester: string;
        requiredFeeders: bigint;
        rewardAmount: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  feedToken: TypedContractMethod<[], [string], "view">;

  feederLicense: TypedContractMethod<[], [string], "view">;

  feeders: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        registered: boolean;
        rank: bigint;
        xp: bigint;
        totalFeeds: bigint;
        stakedAmount: bigint;
        unstakeRequestTime: bigint;
        dailyGrabCount: bigint;
        lastGrabDate: bigint;
      }
    ],
    "view"
  >;

  getConsensusPrice: TypedContractMethod<
    [orderId: BytesLike],
    [
      [bigint, bigint, boolean] & {
        price: bigint;
        timestamp: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;

  getFeederInfo: TypedContractMethod<
    [feederAddr: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint] & {
        registered: boolean;
        rank: bigint;
        xp: bigint;
        totalFeeds: bigint;
        stakedAmount: bigint;
        pendingRewards: bigint;
      }
    ],
    "view"
  >;

  getOrderFeeders: TypedContractMethod<
    [orderId: BytesLike],
    [string[]],
    "view"
  >;

  grabOrder: TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;

  initialize: TypedContractMethod<
    [
      owner_: AddressLike,
      feedToken_: AddressLike,
      consensus_: AddressLike,
      rewardPenalty_: AddressLike,
      feederLicense_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isProtocolAuthorized: TypedContractMethod<
    [protocol: AddressLike],
    [boolean],
    "view"
  >;

  maxDailyGrabByRank: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  minStakeByRank: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerFeeder: TypedContractMethod<
    [stakeAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestFeed: TypedContractMethod<
    [
      orderId: BytesLike,
      requiredFeeders: BigNumberish,
      rewardAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  requestUnstake: TypedContractMethod<[], [void], "nonpayable">;

  rewardPenalty: TypedContractMethod<[], [string], "view">;

  setAuthorizedProtocol: TypedContractMethod<
    [protocol: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  settleOrder: TypedContractMethod<
    [orderId: BytesLike, rewardAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  totalFeeders: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstakeCooldown: TypedContractMethod<[], [bigint], "view">;

  updateMinStake: TypedContractMethod<
    [rank: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateSubContracts: TypedContractMethod<
    [
      consensus_: AddressLike,
      rewardPenalty_: AddressLike,
      feederLicense_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  updateUnstakeCooldown: TypedContractMethod<
    [cooldown: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  xpThresholds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedProtocols"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "awardXP"
  ): TypedContractMethod<
    [feederAddr: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "consensus"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "engineOrders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean] & {
        orderId: string;
        rewardAmount: bigint;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "feedRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        requester: string;
        requiredFeeders: bigint;
        rewardAmount: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "feedToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feederLicense"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeders"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        registered: boolean;
        rank: bigint;
        xp: bigint;
        totalFeeds: bigint;
        stakedAmount: bigint;
        unstakeRequestTime: bigint;
        dailyGrabCount: bigint;
        lastGrabDate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConsensusPrice"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [
      [bigint, bigint, boolean] & {
        price: bigint;
        timestamp: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeederInfo"
  ): TypedContractMethod<
    [feederAddr: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint] & {
        registered: boolean;
        rank: bigint;
        xp: bigint;
        totalFeeds: bigint;
        stakedAmount: bigint;
        pendingRewards: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderFeeders"
  ): TypedContractMethod<[orderId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grabOrder"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      owner_: AddressLike,
      feedToken_: AddressLike,
      consensus_: AddressLike,
      rewardPenalty_: AddressLike,
      feederLicense_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isProtocolAuthorized"
  ): TypedContractMethod<[protocol: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxDailyGrabByRank"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "minStakeByRank"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerFeeder"
  ): TypedContractMethod<[stakeAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestFeed"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      requiredFeeders: BigNumberish,
      rewardAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestUnstake"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardPenalty"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedProtocol"
  ): TypedContractMethod<
    [protocol: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleOrder"
  ): TypedContractMethod<
    [orderId: BytesLike, rewardAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalFeeders"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateMinStake"
  ): TypedContractMethod<
    [rank: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSubContracts"
  ): TypedContractMethod<
    [
      consensus_: AddressLike,
      rewardPenalty_: AddressLike,
      feederLicense_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateUnstakeCooldown"
  ): TypedContractMethod<[cooldown: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "xpThresholds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "FeedRequested"
  ): TypedContractEvent<
    FeedRequestedEvent.InputTuple,
    FeedRequestedEvent.OutputTuple,
    FeedRequestedEvent.OutputObject
  >;
  getEvent(
    key: "FeederRankUpdated"
  ): TypedContractEvent<
    FeederRankUpdatedEvent.InputTuple,
    FeederRankUpdatedEvent.OutputTuple,
    FeederRankUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeederRegistered"
  ): TypedContractEvent<
    FeederRegisteredEvent.InputTuple,
    FeederRegisteredEvent.OutputTuple,
    FeederRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OrderGrabbed"
  ): TypedContractEvent<
    OrderGrabbedEvent.InputTuple,
    OrderGrabbedEvent.OutputTuple,
    OrderGrabbedEvent.OutputObject
  >;
  getEvent(
    key: "OrderSettled"
  ): TypedContractEvent<
    OrderSettledEvent.InputTuple,
    OrderSettledEvent.OutputTuple,
    OrderSettledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolAuthorized"
  ): TypedContractEvent<
    ProtocolAuthorizedEvent.InputTuple,
    ProtocolAuthorizedEvent.OutputTuple,
    ProtocolAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "UnstakeRequested"
  ): TypedContractEvent<
    UnstakeRequestedEvent.InputTuple,
    UnstakeRequestedEvent.OutputTuple,
    UnstakeRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "XPAwarded"
  ): TypedContractEvent<
    XPAwardedEvent.InputTuple,
    XPAwardedEvent.OutputTuple,
    XPAwardedEvent.OutputObject
  >;

  filters: {
    "FeedRequested(bytes32,address,uint256,uint256)": TypedContractEvent<
      FeedRequestedEvent.InputTuple,
      FeedRequestedEvent.OutputTuple,
      FeedRequestedEvent.OutputObject
    >;
    FeedRequested: TypedContractEvent<
      FeedRequestedEvent.InputTuple,
      FeedRequestedEvent.OutputTuple,
      FeedRequestedEvent.OutputObject
    >;

    "FeederRankUpdated(address,uint8,uint8)": TypedContractEvent<
      FeederRankUpdatedEvent.InputTuple,
      FeederRankUpdatedEvent.OutputTuple,
      FeederRankUpdatedEvent.OutputObject
    >;
    FeederRankUpdated: TypedContractEvent<
      FeederRankUpdatedEvent.InputTuple,
      FeederRankUpdatedEvent.OutputTuple,
      FeederRankUpdatedEvent.OutputObject
    >;

    "FeederRegistered(address,uint256)": TypedContractEvent<
      FeederRegisteredEvent.InputTuple,
      FeederRegisteredEvent.OutputTuple,
      FeederRegisteredEvent.OutputObject
    >;
    FeederRegistered: TypedContractEvent<
      FeederRegisteredEvent.InputTuple,
      FeederRegisteredEvent.OutputTuple,
      FeederRegisteredEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OrderGrabbed(bytes32,address)": TypedContractEvent<
      OrderGrabbedEvent.InputTuple,
      OrderGrabbedEvent.OutputTuple,
      OrderGrabbedEvent.OutputObject
    >;
    OrderGrabbed: TypedContractEvent<
      OrderGrabbedEvent.InputTuple,
      OrderGrabbedEvent.OutputTuple,
      OrderGrabbedEvent.OutputObject
    >;

    "OrderSettled(bytes32,uint256,uint256)": TypedContractEvent<
      OrderSettledEvent.InputTuple,
      OrderSettledEvent.OutputTuple,
      OrderSettledEvent.OutputObject
    >;
    OrderSettled: TypedContractEvent<
      OrderSettledEvent.InputTuple,
      OrderSettledEvent.OutputTuple,
      OrderSettledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProtocolAuthorized(address,bool)": TypedContractEvent<
      ProtocolAuthorizedEvent.InputTuple,
      ProtocolAuthorizedEvent.OutputTuple,
      ProtocolAuthorizedEvent.OutputObject
    >;
    ProtocolAuthorized: TypedContractEvent<
      ProtocolAuthorizedEvent.InputTuple,
      ProtocolAuthorizedEvent.OutputTuple,
      ProtocolAuthorizedEvent.OutputObject
    >;

    "Staked(address,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "UnstakeRequested(address,uint256)": TypedContractEvent<
      UnstakeRequestedEvent.InputTuple,
      UnstakeRequestedEvent.OutputTuple,
      UnstakeRequestedEvent.OutputObject
    >;
    UnstakeRequested: TypedContractEvent<
      UnstakeRequestedEvent.InputTuple,
      UnstakeRequestedEvent.OutputTuple,
      UnstakeRequestedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;

    "XPAwarded(address,uint256,string)": TypedContractEvent<
      XPAwardedEvent.InputTuple,
      XPAwardedEvent.OutputTuple,
      XPAwardedEvent.OutputObject
    >;
    XPAwarded: TypedContractEvent<
      XPAwardedEvent.InputTuple,
      XPAwardedEvent.OutputTuple,
      XPAwardedEvent.OutputObject
    >;
  };
}
