/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FeedConsensusInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "authorizedOperators"
      | "batchSubmitPriceHash"
      | "commitWindow"
      | "commits"
      | "computePriceHash"
      | "createOrder"
      | "disputeOrder"
      | "getCommit"
      | "getConsensusPrice"
      | "getOrderPhase"
      | "getRevealedFeeders"
      | "initialize"
      | "maxDeviationBps"
      | "orders"
      | "owner"
      | "proxiableUUID"
      | "renounceOwnership"
      | "revealPrice"
      | "revealWindow"
      | "revealedFeeders"
      | "setOperator"
      | "settleOrder"
      | "submitConsensus"
      | "submitPriceHash"
      | "transferOwnership"
      | "updateMaxDeviation"
      | "updateWindows"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConsensusReached"
      | "Initialized"
      | "OperatorUpdated"
      | "OrderCreated"
      | "OrderDisputed"
      | "OwnershipTransferred"
      | "PriceCommitted"
      | "PriceRevealed"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSubmitPriceHash",
    values: [BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "commitWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commits",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computePriceHash",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [BytesLike, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeOrder",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommit",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConsensusPrice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderPhase",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRevealedFeeders",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxDeviationBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "orders", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealPrice",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealedFeeders",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "settleOrder",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitConsensus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPriceHash",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaxDeviation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWindows",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSubmitPriceHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "computePriceHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCommit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getConsensusPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevealedFeeders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxDeviationBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealedFeeders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitConsensus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPriceHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaxDeviation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWindows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace ConsensusReachedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    consensusPrice: BigNumberish,
    participantCount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    consensusPrice: bigint,
    participantCount: bigint
  ];
  export interface OutputObject {
    orderId: string;
    consensusPrice: bigint;
    participantCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [operator: AddressLike, authorized: boolean];
  export type OutputTuple = [operator: string, authorized: boolean];
  export interface OutputObject {
    operator: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    symbol: string,
    notionalAmount: BigNumberish,
    quorum: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    symbol: string,
    notionalAmount: bigint,
    quorum: bigint
  ];
  export interface OutputObject {
    orderId: string;
    symbol: string;
    notionalAmount: bigint;
    quorum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderDisputedEvent {
  export type InputTuple = [orderId: BytesLike, reason: string];
  export type OutputTuple = [orderId: string, reason: string];
  export interface OutputObject {
    orderId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceCommittedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    feeder: AddressLike,
    priceHash: BytesLike
  ];
  export type OutputTuple = [
    orderId: string,
    feeder: string,
    priceHash: string
  ];
  export interface OutputObject {
    orderId: string;
    feeder: string;
    priceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceRevealedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    feeder: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [orderId: string, feeder: string, price: bigint];
  export interface OutputObject {
    orderId: string;
    feeder: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FeedConsensus extends BaseContract {
  connect(runner?: ContractRunner | null): FeedConsensus;
  waitForDeployment(): Promise<this>;

  interface: FeedConsensusInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  authorizedOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  batchSubmitPriceHash: TypedContractMethod<
    [orderIds: BytesLike[], priceHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;

  commitWindow: TypedContractMethod<[], [bigint], "view">;

  commits: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [string, bigint, boolean, boolean, bigint] & {
        priceHash: string;
        revealedPrice: bigint;
        committed: boolean;
        revealed: boolean;
        commitTime: bigint;
      }
    ],
    "view"
  >;

  computePriceHash: TypedContractMethod<
    [price: BigNumberish, salt: BytesLike],
    [string],
    "view"
  >;

  createOrder: TypedContractMethod<
    [
      orderId: BytesLike,
      symbol: string,
      notionalAmount: BigNumberish,
      quorum: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  disputeOrder: TypedContractMethod<
    [orderId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getCommit: TypedContractMethod<
    [orderId: BytesLike, feeder: AddressLike],
    [
      [string, bigint, boolean, boolean] & {
        priceHash: string;
        revealedPrice: bigint;
        committed: boolean;
        revealed: boolean;
      }
    ],
    "view"
  >;

  getConsensusPrice: TypedContractMethod<
    [orderId: BytesLike],
    [bigint],
    "view"
  >;

  getOrderPhase: TypedContractMethod<[orderId: BytesLike], [bigint], "view">;

  getRevealedFeeders: TypedContractMethod<
    [orderId: BytesLike],
    [string[]],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      owner_: AddressLike,
      commitWindow_: BigNumberish,
      revealWindow_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  maxDeviationBps: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        orderId: string;
        symbol: string;
        notionalAmount: bigint;
        phase: bigint;
        commitDeadline: bigint;
        revealDeadline: bigint;
        consensusPrice: bigint;
        requiredQuorum: bigint;
        commitCount: bigint;
        revealCount: bigint;
        creator: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revealPrice: TypedContractMethod<
    [orderId: BytesLike, price: BigNumberish, salt: BytesLike],
    [void],
    "nonpayable"
  >;

  revealWindow: TypedContractMethod<[], [bigint], "view">;

  revealedFeeders: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  setOperator: TypedContractMethod<
    [operator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  settleOrder: TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;

  submitConsensus: TypedContractMethod<
    [orderId: BytesLike, consensusPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitPriceHash: TypedContractMethod<
    [orderId: BytesLike, priceHash: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateMaxDeviation: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateWindows: TypedContractMethod<
    [commitWindow_: BigNumberish, revealWindow_: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizedOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchSubmitPriceHash"
  ): TypedContractMethod<
    [orderIds: BytesLike[], priceHashes: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "commits"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [string, bigint, boolean, boolean, bigint] & {
        priceHash: string;
        revealedPrice: bigint;
        committed: boolean;
        revealed: boolean;
        commitTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "computePriceHash"
  ): TypedContractMethod<
    [price: BigNumberish, salt: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      symbol: string,
      notionalAmount: BigNumberish,
      quorum: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeOrder"
  ): TypedContractMethod<
    [orderId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCommit"
  ): TypedContractMethod<
    [orderId: BytesLike, feeder: AddressLike],
    [
      [string, bigint, boolean, boolean] & {
        priceHash: string;
        revealedPrice: bigint;
        committed: boolean;
        revealed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConsensusPrice"
  ): TypedContractMethod<[orderId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOrderPhase"
  ): TypedContractMethod<[orderId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRevealedFeeders"
  ): TypedContractMethod<[orderId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      owner_: AddressLike,
      commitWindow_: BigNumberish,
      revealWindow_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "maxDeviationBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        orderId: string;
        symbol: string;
        notionalAmount: bigint;
        phase: bigint;
        commitDeadline: bigint;
        revealDeadline: bigint;
        consensusPrice: bigint;
        requiredQuorum: bigint;
        commitCount: bigint;
        revealCount: bigint;
        creator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealPrice"
  ): TypedContractMethod<
    [orderId: BytesLike, price: BigNumberish, salt: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revealWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealedFeeders"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [operator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleOrder"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitConsensus"
  ): TypedContractMethod<
    [orderId: BytesLike, consensusPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitPriceHash"
  ): TypedContractMethod<
    [orderId: BytesLike, priceHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMaxDeviation"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWindows"
  ): TypedContractMethod<
    [commitWindow_: BigNumberish, revealWindow_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "ConsensusReached"
  ): TypedContractEvent<
    ConsensusReachedEvent.InputTuple,
    ConsensusReachedEvent.OutputTuple,
    ConsensusReachedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderDisputed"
  ): TypedContractEvent<
    OrderDisputedEvent.InputTuple,
    OrderDisputedEvent.OutputTuple,
    OrderDisputedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceCommitted"
  ): TypedContractEvent<
    PriceCommittedEvent.InputTuple,
    PriceCommittedEvent.OutputTuple,
    PriceCommittedEvent.OutputObject
  >;
  getEvent(
    key: "PriceRevealed"
  ): TypedContractEvent<
    PriceRevealedEvent.InputTuple,
    PriceRevealedEvent.OutputTuple,
    PriceRevealedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "ConsensusReached(bytes32,uint256,uint256)": TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;
    ConsensusReached: TypedContractEvent<
      ConsensusReachedEvent.InputTuple,
      ConsensusReachedEvent.OutputTuple,
      ConsensusReachedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OperatorUpdated(address,bool)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "OrderCreated(bytes32,string,uint256,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderDisputed(bytes32,string)": TypedContractEvent<
      OrderDisputedEvent.InputTuple,
      OrderDisputedEvent.OutputTuple,
      OrderDisputedEvent.OutputObject
    >;
    OrderDisputed: TypedContractEvent<
      OrderDisputedEvent.InputTuple,
      OrderDisputedEvent.OutputTuple,
      OrderDisputedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceCommitted(bytes32,address,bytes32)": TypedContractEvent<
      PriceCommittedEvent.InputTuple,
      PriceCommittedEvent.OutputTuple,
      PriceCommittedEvent.OutputObject
    >;
    PriceCommitted: TypedContractEvent<
      PriceCommittedEvent.InputTuple,
      PriceCommittedEvent.OutputTuple,
      PriceCommittedEvent.OutputObject
    >;

    "PriceRevealed(bytes32,address,uint256)": TypedContractEvent<
      PriceRevealedEvent.InputTuple,
      PriceRevealedEvent.OutputTuple,
      PriceRevealedEvent.OutputObject
    >;
    PriceRevealed: TypedContractEvent<
      PriceRevealedEvent.InputTuple,
      PriceRevealedEvent.OutputTuple,
      PriceRevealedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
