/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RewardPenaltyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "applyPenalty"
      | "authorizedOperators"
      | "banUntil"
      | "canGrabOrder"
      | "claimRewards"
      | "daoTreasury"
      | "distributeRewards"
      | "feedToken"
      | "getPenaltyCount"
      | "getPenaltyRecord"
      | "initialize"
      | "owner"
      | "penaltyBanDays"
      | "penaltyHistory"
      | "penaltySlashBps"
      | "pendingRewards"
      | "permanentlyBanned"
      | "platformTreasury"
      | "proxiableUUID"
      | "renounceOwnership"
      | "rewardSplit"
      | "setOperator"
      | "totalRewardsEarned"
      | "transferOwnership"
      | "updateRewardSplit"
      | "updateTreasuries"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeederBanned"
      | "FeederPermanentlyBanned"
      | "Initialized"
      | "OperatorUpdated"
      | "OwnershipTransferred"
      | "PenaltyApplied"
      | "RewardClaimed"
      | "RewardDistributed"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyPenalty",
    values: [AddressLike, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "banUntil",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canGrabOrder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "daoTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeRewards",
    values: [BytesLike, AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feedToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPenaltyCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPenaltyRecord",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "penaltyBanDays",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "penaltyHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "penaltySlashBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "permanentlyBanned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardSplit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRewardsEarned",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRewardSplit",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTreasuries",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "banUntil", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canGrabOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "daoTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feedToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPenaltyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPenaltyRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "penaltyBanDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "penaltyHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "penaltySlashBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "permanentlyBanned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRewardsEarned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRewardSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTreasuries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace FeederBannedEvent {
  export type InputTuple = [feeder: AddressLike, until: BigNumberish];
  export type OutputTuple = [feeder: string, until: bigint];
  export interface OutputObject {
    feeder: string;
    until: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeederPermanentlyBannedEvent {
  export type InputTuple = [feeder: AddressLike];
  export type OutputTuple = [feeder: string];
  export interface OutputObject {
    feeder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [operator: AddressLike, authorized: boolean];
  export type OutputTuple = [operator: string, authorized: boolean];
  export interface OutputObject {
    operator: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PenaltyAppliedEvent {
  export type InputTuple = [
    feeder: AddressLike,
    level: BigNumberish,
    slashedAmount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    feeder: string,
    level: bigint,
    slashedAmount: bigint,
    reason: string
  ];
  export interface OutputObject {
    feeder: string;
    level: bigint;
    slashedAmount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [feeder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [feeder: string, amount: bigint];
  export interface OutputObject {
    feeder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    totalAmount: BigNumberish,
    feederAmount: BigNumberish,
    platformAmount: BigNumberish,
    daoAmount: BigNumberish,
    burnAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    totalAmount: bigint,
    feederAmount: bigint,
    platformAmount: bigint,
    daoAmount: bigint,
    burnAmount: bigint
  ];
  export interface OutputObject {
    orderId: string;
    totalAmount: bigint;
    feederAmount: bigint;
    platformAmount: bigint;
    daoAmount: bigint;
    burnAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RewardPenalty extends BaseContract {
  connect(runner?: ContractRunner | null): RewardPenalty;
  waitForDeployment(): Promise<this>;

  interface: RewardPenaltyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  applyPenalty: TypedContractMethod<
    [
      feeder: AddressLike,
      level: BigNumberish,
      reason: string,
      stakedAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  authorizedOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  banUntil: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  canGrabOrder: TypedContractMethod<[feeder: AddressLike], [boolean], "view">;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  daoTreasury: TypedContractMethod<[], [string], "view">;

  distributeRewards: TypedContractMethod<
    [orderId: BytesLike, feeders: AddressLike[], totalReward: BigNumberish],
    [void],
    "nonpayable"
  >;

  feedToken: TypedContractMethod<[], [string], "view">;

  getPenaltyCount: TypedContractMethod<[feeder: AddressLike], [bigint], "view">;

  getPenaltyRecord: TypedContractMethod<
    [feeder: AddressLike, index: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        level: bigint;
        reason: string;
        slashedAmount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      owner_: AddressLike,
      feedToken_: AddressLike,
      platformTreasury_: AddressLike,
      daoTreasury_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  penaltyBanDays: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  penaltyHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint] & {
        level: bigint;
        reason: string;
        slashedAmount: bigint;
        timestamp: bigint;
        banUntil: bigint;
      }
    ],
    "view"
  >;

  penaltySlashBps: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  pendingRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  permanentlyBanned: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardSplit: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        feederBps: bigint;
        platformBps: bigint;
        daoBps: bigint;
        burnBps: bigint;
      }
    ],
    "view"
  >;

  setOperator: TypedContractMethod<
    [operator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  totalRewardsEarned: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRewardSplit: TypedContractMethod<
    [
      feederBps: BigNumberish,
      platformBps: BigNumberish,
      daoBps: BigNumberish,
      burnBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateTreasuries: TypedContractMethod<
    [platform: AddressLike, dao: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "applyPenalty"
  ): TypedContractMethod<
    [
      feeder: AddressLike,
      level: BigNumberish,
      reason: string,
      stakedAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "banUntil"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "canGrabOrder"
  ): TypedContractMethod<[feeder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "daoTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "distributeRewards"
  ): TypedContractMethod<
    [orderId: BytesLike, feeders: AddressLike[], totalReward: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feedToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPenaltyCount"
  ): TypedContractMethod<[feeder: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPenaltyRecord"
  ): TypedContractMethod<
    [feeder: AddressLike, index: BigNumberish],
    [
      [bigint, string, bigint, bigint] & {
        level: bigint;
        reason: string;
        slashedAmount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      owner_: AddressLike,
      feedToken_: AddressLike,
      platformTreasury_: AddressLike,
      daoTreasury_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "penaltyBanDays"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "penaltyHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint] & {
        level: bigint;
        reason: string;
        slashedAmount: bigint;
        timestamp: bigint;
        banUntil: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "penaltySlashBps"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingRewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "permanentlyBanned"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardSplit"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        feederBps: bigint;
        platformBps: bigint;
        daoBps: bigint;
        burnBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [operator: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalRewardsEarned"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRewardSplit"
  ): TypedContractMethod<
    [
      feederBps: BigNumberish,
      platformBps: BigNumberish,
      daoBps: BigNumberish,
      burnBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTreasuries"
  ): TypedContractMethod<
    [platform: AddressLike, dao: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "FeederBanned"
  ): TypedContractEvent<
    FeederBannedEvent.InputTuple,
    FeederBannedEvent.OutputTuple,
    FeederBannedEvent.OutputObject
  >;
  getEvent(
    key: "FeederPermanentlyBanned"
  ): TypedContractEvent<
    FeederPermanentlyBannedEvent.InputTuple,
    FeederPermanentlyBannedEvent.OutputTuple,
    FeederPermanentlyBannedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PenaltyApplied"
  ): TypedContractEvent<
    PenaltyAppliedEvent.InputTuple,
    PenaltyAppliedEvent.OutputTuple,
    PenaltyAppliedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "FeederBanned(address,uint256)": TypedContractEvent<
      FeederBannedEvent.InputTuple,
      FeederBannedEvent.OutputTuple,
      FeederBannedEvent.OutputObject
    >;
    FeederBanned: TypedContractEvent<
      FeederBannedEvent.InputTuple,
      FeederBannedEvent.OutputTuple,
      FeederBannedEvent.OutputObject
    >;

    "FeederPermanentlyBanned(address)": TypedContractEvent<
      FeederPermanentlyBannedEvent.InputTuple,
      FeederPermanentlyBannedEvent.OutputTuple,
      FeederPermanentlyBannedEvent.OutputObject
    >;
    FeederPermanentlyBanned: TypedContractEvent<
      FeederPermanentlyBannedEvent.InputTuple,
      FeederPermanentlyBannedEvent.OutputTuple,
      FeederPermanentlyBannedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OperatorUpdated(address,bool)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PenaltyApplied(address,uint8,uint256,string)": TypedContractEvent<
      PenaltyAppliedEvent.InputTuple,
      PenaltyAppliedEvent.OutputTuple,
      PenaltyAppliedEvent.OutputObject
    >;
    PenaltyApplied: TypedContractEvent<
      PenaltyAppliedEvent.InputTuple,
      PenaltyAppliedEvent.OutputTuple,
      PenaltyAppliedEvent.OutputObject
    >;

    "RewardClaimed(address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "RewardDistributed(bytes32,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
